# Generated by Django 4.2 on 2023-05-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_comment_product_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
