# Generated by Django 4.2 on 2023-05-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_purchase_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='customer',
        ),
    ]
