# Generated by Django 4.2 on 2023-05-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_purchase_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
